version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Etc/UTC"
    assignees:
      - "amnweb"
    allow:
      - dependency-name: "pyqt6"
      - dependency-name: "pillow"
      - dependency-name: "pycaw"
      - dependency-name: "cx-freeze"
      - dependency-name: "psutil"
      - dependency-name: "holidays"
      - dependency-name: "icoextract"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
